# Introdução

A presente pesquisa é um trabalho conjunto realizado pelo Instituto Brasileiro de Defesa do Consumidor - IDEC e pelo Núcleo de Direito, Tecnologia e Jurimetria da PUC-SP - NDTJ. O Idec é uma associação de consumidores sem fins lucrativos, independente de empresas, partidos ou governos, voltada para a defesa dos interesses dos direitos e interesses dos consumidores brasileiros. O NDTJ é um núcleo de estudos formado por professores, alunos e pesquisadores da PUC-SP, que tem como objetivo aplicar métodos empíricos quantitativos na compreensão do direito.
As duas entidades uniram sua experiência e especialidade para desenvolver a presente pesquisa, com o objetivo de trazer elementos objetivos para o debate relativo à judicialização da saúde, em especial sobre os impactos da lei 14.454, de 21 de setembro de 2022. A lei 14.454 “dispõe sobre os planos privados de assistência à saúde, para estabelecer critérios que permitam a cobertura de exames ou tratamentos de saúde que não estão incluídos no rol de procedimentos e eventos em saúde suplementar.”
O ano de 2022 trouxe dois importantes eventos relacionados à extensão da cobertura dos planos de saúde de acordo com o rol de procedimentos e eventos em saúde suplementar da ANS (Agência Nacional de Saúde Suplementar). O primeiro evento diz respeito ao entendimento firmado pela 2ª Seção do STJ no julgamento dos recursos especiais nº 1.886.929 e 1.889.704, no seguinte sentido:
- Tese 1. O rol da ANS é taxativo.
- Tese 2.  A operadora de saúde não está obrigada a arcar com procedimento não incluído no rol da ANS se existe, para a cura do paciente, outro procedimento eficaz e seguro já incorporado ao rol.
- Tese 3. A contratação de cobertura ampliada ou a negociação de aditivo contratual para a cobertura de procedimento não incluído no rol da ANS é lícita e possível.
O Congresso Nacional reagiu ao entendimento do STJ com a publicação da Lei nº 14.454, que estabeleceu novos marcos legais para o tema, tornando o rol da ANS não taxativo. A lei basicamente determina que, em caso de procedimento prescrito não incluído no rol, a cobertura deve ser autorizada pela operadora de plano de saúde, desde que:
- Marco 1. Exista comprovação da eficácia baseada em evidências científicas.
- Marco 2. Exista recomendação pela Comissão Nacional de Incorporação de Tecnologias no Sistema Único de Saúde (Conitec).
- Marco 3. Existe, alternativamente ao Marco 2, recomendação de, no mínimo, um órgão de avaliação de tecnologias em saúde com renome internacional.
Parte das discussões gira em torno dos impactos que as diferentes soluções terão no volume de pedidos judiciais de acesso a procedimentos médicos apresentados contra planos de saúde, bem como na consequente inviabilização financeira do sistema como um todo. A preocupação relaciona-se ao possível aumento na quantidade de pedidos judiciais em decorrência da flexibilização do rol, nos termos em que estabelecido pela lei 14.454.
No intuito de contribuir para esse debate, foram elaborada as seguintes  questões, que este estudo pretende responder:
Quais são os réus mais frequentes?
Quais são os medicamentos e tratamentos mais recorrentes?
Volume de ações aumentou depois de set 2022?
Em caso positivo, esse aumento está associado à lei 14.454?
Na pesquisa optou-se por coletar processos distribuídos em primeira instância no Tribunal de Justiça de São Paulo (TJSP) com os seguintes assuntos, conforme padronização das tabelas processuais unificadas do Conselho Nacional de Jutiça:
Fornecimento de medicamentos.
Tratamento médico-hospitalar.
Fornecimento de insumos e unidade de terapia intensiva (UTI) ou unidade de cuidados intensivos (UCI).
Quanto ao período, foram consideradas somente ações distribuídas entre 01 de janeiro de 2019 e 09 de setembro de 2023. O período engloba 3 anos e 9 meses antes e um ano após a promulgação da lei 14.454.
Uma vez que não existe busca de processos distribuídos por assunto, foi necessário gerar números de possíveis processos distribuídos durante o período de interesse da pesquisa e posteriormente excluir os assuntos e classes procesuais que não eram de interesse para a pesquisa. Além disso, foram excluídas as ações em que a Fazenda pública municipal ou estadual aparece no polo ativo ou no polo passivo.
Após a aplicação dos filtros, restaram 51.954 processos. No entanto, só foi possível identificar 20.842 decisões liminares distintas de 19.938 processos nos quais constava uma decisão liminar.
