# Introdução

## Pergunta
A Lei nº 14.454/2022 teve impacto sobre o perfil e volume de judicialização contra a saúde suplementar?

## Hipóteses
A Lei do Rol não gerou aumento no volume de demandas judiciais contra a saúde suplementar, pois apenas sedimentou o entendimento jurisprudencial majoritário, consolidado ao longo de muitos anos.
A Lei do Rol não gerou diminuição no volume de demandas administrativas ou judiciais contra a saúde suplementar, pois, na ausência de fiscalização e punição pela ANS, a Lei não terá impactado a prática de negativas indevidas do setor.

## Fonte
Ações distribuídas na 1ª instância do TJSP (e-SAJ)

## Recorte:
Apenas demandas sobre negativa de cobertura contra operadoras (filtrar por assunto e, para excluir demandas contra o SUS, por réu - excluir Fazenda Pública)
Período de janeiro/2019 a junho/2023

## Dados a serem coletados:
Quantidade de demandas distribuídas (por mês)
Menção à Lei º 14.454/2022 nas petições iniciais - criar lista de termos para processamento com GPT
Útil para distinguir o que foi motivado pela Lei, ou respaldado por ela, de outros tipos de demandas relacionadas a negativa de cobertura
Data de decisão sobre pedido liminar (caso haja)

## Prazo: 60 a 90 dias (até novembro de 2023)


## Possíveis limitações:
Erros na classificação dos processos por assunto - coletaremos algumas ações impertinentes e deixaremos de fora outras pertinentes
Dado o curto tempo desde a publicação da lei, dificuldade de dimensionar como e se impactou tempo de julgamento, padrões de procedência, etc.
Dificuldades de separar impactos na judicialização relacionados à pandemia daqueles relacionados à Lei - a coleta da menção à Lei permite apenas uma aproximação
Dificuldade de levantar doenças/tratamentos pleiteados, mesmo com softwares de processamento, dada a falta de padronização neste tipo de demanda - seja em relação ao CID, à TISS, à RENESES… Decisão, por ora, de não coletar esses dados.
